### ISSUE TITLE
"settings.h" and MQTT Passwort/user

### ISSUE THREAD

**Issue by Feierprinz** [enide-electronics/growatt-sph-spa-esp8266#3]
Hi,

the "settings.h" File is missing in my mind in these repo. On the Webbased configuration, I can`t change/see the MQTT-User and Password for the MQTT Broker.

BR
Swen

**Comment by enide-electronics** [comment]
Hey,
There's no settings.h file in this project. Every setting is available via the web interface of the WIFIManager.

Regarding the MQTT username and password they aren't in the code because I never needed them. Shouldn't be too hard to add.
If I have some time this weekend I will try to make the required changes.

**Comment by enide-electronics** [comment]
This is being addressed in #4 .
I just need to run a few more tests before merging it to master and creating the release files.

**Comment by enide-electronics** [comment]
MQTT authentication is now available on the master branch and on the pre-built binaries.
Please use the new [ release 2.2](https://github.com/enide-electronics/growatt-sph-spa-esp8266/releases/tag/2.2)
